name: stackfood_multivendor
description: A new Flutter application.
publish_to: 'none' #
version: 1.1.21+22

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  get:
  shared_preferences:
  connectivity_plus:
  path_provider:
  url_strategy:
  pin_code_fields:
  dots_indicator:
  star_rating:
  geolocator:
  google_maps_flutter:
  google_maps_flutter_web:
  shimmer_animation:
  image_picker:
  universal_html:
  flutter_inappwebview: 
  url_launcher:
  http:
  pointer_interceptor:
  flutter_rating_bar:
  phone_numbers_parser:
  country_code_picker:
  cached_network_image:
  google_sign_in:
  google_sign_in_web:
  scratcher: any
  pull_to_refresh:


  flutter_facebook_auth:
  photo_view:
  dotted_border:
  custom_rating_bar:
  share_plus:
  custom_map_markers:
  image_compression_flutter:
  card_swiper:
  flutter_staggered_grid_view:
  image_cropper:
  flutter_otp_text_field:
  expandable_bottom_sheet:
  uni_links:
  sign_in_with_apple:
  flutter_html:
  flutter_widget_from_html:
  intl:
  flutter_slidable:

  just_the_tooltip:
  animated_flip_counter:
  meta_seo:
  fluttertoast:
  marquee:
  syncfusion_flutter_datepicker: ^24.1.45
  firebase_crashlytics:
  file_picker:
  path:
  carousel_slider:
  http_parser:
  flutter_svg:
  icons_launcher:
  change_app_package_name:
  flutter_polyline_points:
  custom_info_window:
  auto_scroll_text:
  lottie:
  dotted_line:
  animated_toggle_switch:
  dropdown_button2:
  geocoding:

dependency_overrides:
  firebase_crashlytics:
  flutter_widget_from_html_core:
  archive:
  win32:
  flutter_local_notifications:
  firebase_core:

  firebase_messaging: ^15.1.0



icons_launcher:
 image_path: "assets/image/logo.png"
 platforms:
    android:
      enable: true
    ios:
      enable: true

#  image_path: "assets/image/logo.png"
#  platforms:
#      android:
#        enable: true
#      ios:
#        enable: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/map/
    - assets/animation/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
#        - asset: assets/font/Poppins-SemiBold.ttf
#          weight: 600


    - family: Proxima Nova
      fonts:
        - asset: assets/font/Proxima Nova Regular.ttf
          weight: 400
        - asset: assets/font/Proxima Nova Medium.ttf
          weight: 500
        - asset: assets/font/Proxima Nova Bold.ttf
          weight: 700
        - asset: assets/font/Proxima Nova Black.ttf
          weight: 900














#name: stackfood_multivendor
#description: A new Flutter application.
#publish_to: 'none' #
#version: 1.0.0+1
#
#environment:
#  sdk: '>=3.2.1 <4.0.0'
#
#dependencies:
#  flutter:
#    sdk: flutter
#  flutter_localizations:
#    sdk: flutter
#
#  get: ^4.6.6
#  shared_preferences: ^2.0.15
#  connectivity_plus: ^5.0.2
#  firebase_core: ^2.4.1
#  firebase_messaging: ^14.2.1
#  flutter_local_notifications: ^16.3.0
#  path_provider: ^2.0.8
#  url_strategy: ^0.2.0
#  pin_code_fields: ^8.0.1
#  dots_indicator: ^3.0.0
#  star_rating: any
#  geolocator: ^10.1.0
#  google_maps_flutter: any
#  google_maps_flutter_web: any
#  shimmer_animation: ^2.1.0+1
#  image_picker: ^1.0.7
#  universal_html: ^2.0.8
#  flutter_inappwebview: ^6.1.5
#  url_launcher: ^6.0.17
#  http: any
#  pointer_interceptor: ^0.10.1
#  flutter_rating_bar: ^4.0.1
#  phone_numbers_parser: ^8.1.3
#  country_code_picker: ^3.0.0
#  cached_network_image: ^3.3.0
#  google_sign_in: ^5.4.2
#  google_sign_in_web: ^0.10.2
#  scratcher: any
#
#  flutter_facebook_auth: ^6.0.4
#  photo_view: ^0.14.0
#  dotted_border: ^2.0.0+2
#  custom_rating_bar: ^3.0.0
#  share_plus: ^7.2.1
#  custom_map_markers: ^0.0.2+1
#  image_compression_flutter: ^1.0.4
#  card_swiper: ^3.0.1
#  flutter_staggered_grid_view: ^0.7.0
#  image_cropper: any
#  flutter_otp_text_field: ^1.2.0
#  expandable_bottom_sheet: ^1.1.1+1
#  uni_links: ^0.5.1
#  sign_in_with_apple: ^5.0.0
#  flutter_html: 3.0.0-alpha.5
#  flutter_widget_from_html: ^0.14.11
#  intl:
#  flutter_slidable: ^3.0.0
#
#  just_the_tooltip: ^0.0.12
#  animated_flip_counter: ^0.2.0
#  meta_seo: ^3.0.5
#  fluttertoast: ^8.2.4
#  marquee: ^2.2.3
#  syncfusion_flutter_datepicker: ^24.1.45
#  firebase_crashlytics: ^3.4.3
#  file_picker: ^6.2.0
#  path: ^1.8.2
#  carousel_slider: ^5.0.0
#  http_parser: ^4.0.2
#  flutter_svg: ^2.0.10+1
#  icons_launcher: ^2.1.7
#  change_app_package_name: ^1.1.0
#  flutter_polyline_points: ^2.0.0
#  custom_info_window: ^1.0.1
#  auto_scroll_text: ^0.0.7
#  lottie: ^3.1.1
#  dotted_line: ^3.2.2
#  animated_toggle_switch: any
#  dropdown_button2: ^2.3.9
#  geocoding: ^3.0.0
#
#
#icons_launcher:
# image_path: "assets/image/logo.png"
# platforms:
#    android:
#      enable: true
#    ios:
#      enable: true
#
##  image_path: "assets/image/logo.png"
##  platforms:
##      android:
##        enable: true
##      ios:
##        enable: true
#
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#
#  flutter_lints: ^3.0.1
#
#flutter:
#  uses-material-design: true
#
#  assets:
#    - assets/image/
#    - assets/language/
#    - assets/map/
#    - assets/animation/
#
#  fonts:
#    - family: Poppins
#      fonts:
#        - asset: assets/font/Poppins-Regular.ttf
##        - asset: assets/font/Poppins-SemiBold.ttf
##          weight: 600
#
#
#    - family: Proxima Nova
#      fonts:
#        - asset: assets/font/Proxima Nova Regular.ttf
#          weight: 400
#        - asset: assets/font/Proxima Nova Medium.ttf
#          weight: 500
#        - asset: assets/font/Proxima Nova Bold.ttf
#          weight: 700
#        - asset: assets/font/Proxima Nova Black.ttf
#          weight: 900